### ISSUE TITLE
[Feature Request] Lookup from Context Menu in Preview

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#26]
The rationale: Many of us use _Dataview_ to show content in lists and tables. These can’t be seen in edit mode, obviously. Would be nice if words could be clicked in preview mode, and a context menu shown with "lookup". Links might present a problem though—didn’t find a way to highlight part of a link (say, a note’s file name).

**Comment by phibr0** [comment]
This is certainly possible, but since Obsidian only has a API for Edit Mode, if I would want to create Custom Context Menu Entries for Preview, I would have to override existing functionalities. Something like Copy isn't a big deal, I could easily implement that on my own, but I really dont want to reimplement Entries for all of this: 

![image](https://user-images.githubusercontent.com/59741989/126822002-e5dfcc90-b2e0-43c1-9e16-a91e91b6879c.png)

**Comment by Moonbase59** [comment]
Yeah, that’s right. Too bad, but we can’t have everything … ;-)

**Comment by Moonbase59** [comment]
I’d be fine with closing this for now, or do you want to keep it open?

**Comment by phibr0** [comment]
Once you update it should work in Preview!

**Comment by Moonbase59** [comment]
Now how cool is that! Thanks for implementing!
